CommunityService.create!(id: 1, event_name: 'Try a Tri', date_of_event: Time.now, link_to_event: 'somelink.com', user_id: 1, hours_volunteered: 3)
CommunityService.create!(id: 2, event_name: 'Try a Tri', date_of_event: 1.day.from_now, link_to_event: 'somelink.com', user_id: 2, hours_volunteered: 3)
CommunityService.create!(id: 3, event_name: 'Try a Tri', date_of_event: 1.day.from_now, link_to_event: 'somelink.com', user_id: 4, hours_volunteered: 3)
CommunityService.create!(id: 4, event_name: 'Dog Walking', date_of_event: 15.day.from_now, link_to_event: 'somelink.com', user_id: 1, hours_volunteered: 1)
CommunityService.create!(id: 5, event_name: 'Food Shelter', date_of_event: 19.day.from_now, link_to_event: 'somelink.com', user_id: 6, hours_volunteered: 5)
CommunityService.create!(id: 6, event_name: 'Food Shelter', date_of_event: 27.days.from_now, link_to_event: 'somelink.com', user_id: 5, hours_volunteered: 5)
CommunityService.create!(id: 7, event_name: 'Clean up neighborhood', date_of_event: 1.months.from_now, link_to_event: 'somelink.com', user_id: 4, hours_volunteered: 4)
CommunityService.create!(id: 8, event_name: 'Clean up neighborhood', date_of_event: 1.months.from_now, link_to_event: 'somelink.com', user_id: 3, hours_volunteered: 4)
CommunityService.create!(id: 9, event_name: 'Clean up neighborhood', date_of_event: 1.months.from_now, link_to_event: 'somelink.com', user_id: 2, hours_volunteered: 4)
CommunityService.create!(id: 10, event_name: 'Dog Walking', date_of_event: 2.months.from_now, link_to_event: 'somelink.com', user_id: 1, hours_volunteered: 2)
CommunityService.create!(id: 11, event_name: 'Leadership Conference', date_of_event: 3.months.from_now, link_to_event: 'somelink.com', user_id: 5, hours_volunteered: 3)
CommunityService.create!(id: 12, event_name: 'Leadership Conference', date_of_event: 4.months.from_now, link_to_event: 'somelink.com', user_id: 1, hours_volunteered: 3)

