interview_questionnaires = [
    {
        user_id: 1,
        date_of_birth: '12-01-99',
        hometown: 'North Attleboro, MA',
        current_residence_id: 1,
        room_number: '123',
        grade_point_average: '3.2',
        major: 'Software Engineering',
        year_in_school: 1,
        nickname: 'Tall Paul',
        outside_activities: 'student government, photo club',
        hobbies: 'skiing, hockey, soccer',
        brothers_you_know: 'paul, paul, tim. tim',
        rush_events_attended: 'aoe, aoe, aoe, aoe, aoe, ,ae, aoe',
        reason_for_rushing: 'Something something something because I want to join'
    },
    {
        user_id: 2,
        date_of_birth: '22-03-99',
        hometown: 'Foxboro, MA',
        current_residence_id: 3,
        room_number: '345',
        grade_point_average: '2.4',
        major: 'Mechanical Engineering',
        year_in_school: 2,
        nickname: '',
        outside_activities: 'student government, photo club',
        hobbies: 'skiing, hockey, soccer',
        brothers_you_know: 'paul, paul, tim. tim, dan',
        rush_events_attended: 'AOE, AOE',
        reason_for_rushing: 'Something something something because I want to join'
    },
    {
        user_id: 3,
        date_of_birth: '11-12-00',
        hometown: 'Boston, MA',
        current_residence_id: 3,
        room_number: '765',
        grade_point_average: '1.3',
        major: 'Mechanical Engineering',
        year_in_school: 3,
        nickname: 'The Tallest Paul',
        outside_activities: 'student government, photo club',
        hobbies: 'skiing, hockey, soccer',
        brothers_you_know: 'paul, paul, tim',
        rush_events_attended: 'aoe, aoe, aoe, ,ae',
        reason_for_rushing: 'Something something something because I want to join'
    },
    {
        user_id: 4,
        date_of_birth: '25-07-99',
        hometown: 'Porstmouth, NH',
        current_residence_id: 4,
        room_number: '987',
        grade_point_average: '3.3',
        major: 'Civil Engineering',
        year_in_school: 1,
        nickname: '',
        outside_activities: 'student government, photo club',
        hobbies: 'skiing, hockey, soccer',
        brothers_you_know: 'paul, paul, tim. tim',
        rush_events_attended: 'aoe, aoe, aoe, ,ae, aoe, OEU',
        reason_for_rushing: 'Something something something because I want to join'
    },
    {
        user_id: 5,
        date_of_birth: '28-08-98',
        hometown: 'Rochester, NY',
        current_residence_id: 2,
        room_number: '775',
        grade_point_average: '4.0',
        major: 'Electrical Engineering',
        year_in_school: 1,
        nickname: '',
        outside_activities: 'student government, photo club',
        hobbies: 'skiing, hockey, soccer',
        brothers_you_know: 'paul, paul, tim. tim, dan, rick',
        rush_events_attended: 'aoe, aoe, aoe, ,ae, aoe',
        reason_for_rushing: 'Something something something because I want to join'
    },
]
InterviewQuestionnaire.create!(interview_questionnaires)