#Used for allowing users to format text
#Bellow are the options for reformatting the text
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
toolbar:
  - styleselect | bold italic | undo redo | fontselect | fontsizeselect | image | link
plugins:
  - link
  - table
  - fullscreen
  - image