theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
toolbar:
  - styleselect | bold italic | undo redo | fontselect | fontsizeselect 
  - image | link
plugins:
  - table
  - fullscreen
