require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AlumniEternalsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # AlumniEternal. As you add validations to AlumniEternal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
        user_id: 1,
        first_name: 'Paul',
        last_name: 'Darragh',
        picture: '',
        description: 'He was a good guy'
    }
  }

  let(:invalid_attributes) {
    {
        user_id: nil,
        first_name: nil,
        last_name: nil,
        picture: nil,
        description: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlumniEternalsController. Be sure to keep this updated too.
  let(:valid_session) {
    @user = FactoryGirl.create(:user)
    sign_in :user, @user
  }

  describe "GET #index" do
    it "assigns all alumni_eternals as @alumni_eternals" do
      alumni_eternal = AlumniEternal.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:alumni_eternals)).to eq([alumni_eternal])
    end
  end

  describe "GET #show" do
    it "assigns the requested alumni_eternal as @alumni_eternal" do
      alumni_eternal = AlumniEternal.create! valid_attributes
      get :show, {:id => alumni_eternal.to_param}, valid_session
      expect(assigns(:alumni_eternal)).to eq(alumni_eternal)
    end
  end

  describe "GET #new" do
    it "assigns a new alumni_eternal as @alumni_eternal" do
      get :new, {}, valid_session
      expect(assigns(:alumni_eternal)).to be_a_new(AlumniEternal)
    end
  end

  describe "GET #edit" do
    it "assigns the requested alumni_eternal as @alumni_eternal" do
      alumni_eternal = AlumniEternal.create! valid_attributes
      get :edit, {:id => alumni_eternal.to_param}, valid_session
      expect(assigns(:alumni_eternal)).to eq(alumni_eternal)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AlumniEternal" do
        expect {
          post :create, {:alumni_eternal => valid_attributes}, valid_session
        }.to change(AlumniEternal, :count).by(1)
      end

      it "assigns a newly created alumni_eternal as @alumni_eternal" do
        post :create, {:alumni_eternal => valid_attributes}, valid_session
        expect(assigns(:alumni_eternal)).to be_a(AlumniEternal)
        expect(assigns(:alumni_eternal)).to be_persisted
      end

      it "redirects to the created alumni_eternal" do
        post :create, {:alumni_eternal => valid_attributes}, valid_session
        expect(response).to redirect_to(AlumniEternal.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved alumni_eternal as @alumni_eternal" do
        post :create, {:alumni_eternal => invalid_attributes}, valid_session
        expect(assigns(:alumni_eternal)).to be_a_new(AlumniEternal)
      end

      it "re-renders the 'new' template" do
        post :create, {:alumni_eternal => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            user_id: 1,
            first_name: 'Paul',
            last_name: 'Darragh',
            picture: '',
            description: 'He was a really good guy'
        }
      }

      it "updates the requested alumni_eternal" do
        alumni_eternal = AlumniEternal.create! valid_attributes
        put :update, {:id => alumni_eternal.to_param, :alumni_eternal => new_attributes}, valid_session
        alumni_eternal.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested alumni_eternal as @alumni_eternal" do
        alumni_eternal = AlumniEternal.create! valid_attributes
        put :update, {:id => alumni_eternal.to_param, :alumni_eternal => valid_attributes}, valid_session
        expect(assigns(:alumni_eternal)).to eq(alumni_eternal)
      end

      it "redirects to the alumni_eternal" do
        alumni_eternal = AlumniEternal.create! valid_attributes
        put :update, {:id => alumni_eternal.to_param, :alumni_eternal => valid_attributes}, valid_session
        expect(response).to redirect_to(alumni_eternal)
      end
    end

    context "with invalid params" do
      it "assigns the alumni_eternal as @alumni_eternal" do
        alumni_eternal = AlumniEternal.create! valid_attributes
        put :update, {:id => alumni_eternal.to_param, :alumni_eternal => invalid_attributes}, valid_session
        expect(assigns(:alumni_eternal)).to eq(alumni_eternal)
      end

      it "re-renders the 'edit' template" do
        alumni_eternal = AlumniEternal.create! valid_attributes
        put :update, {:id => alumni_eternal.to_param, :alumni_eternal => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested alumni_eternal" do
      alumni_eternal = AlumniEternal.create! valid_attributes
      expect {
        delete :destroy, {:id => alumni_eternal.to_param}, valid_session
      }.to change(AlumniEternal, :count).by(-1)
    end

    it "redirects to the alumni_eternals list" do
      alumni_eternal = AlumniEternal.create! valid_attributes
      delete :destroy, {:id => alumni_eternal.to_param}, valid_session
      expect(response).to redirect_to(alumni_eternals_url)
    end
  end

end
