require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AlumniEternalStoriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # AlumniEternalStory. As you add validations to AlumniEternalStory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      user_id: 1,
      story: 'Something touching about an alumni',
      alumni_eternal_id: 1
    }
  }

  let(:invalid_attributes) {
    {
        user_id: nil,
        story: nil,
        alumni_eternal_id: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlumniEternalStoriesController. Be sure to keep this updated too.
  let(:valid_session) {
    @user = FactoryGirl.create(:user)
    sign_in :user, @user
  }

  describe "GET #index" do
    it "assigns all alumni_eternal_stories as @alumni_eternal_stories" do
      alumni_eternal_story = AlumniEternalStory.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:alumni_eternal_stories)).to eq([alumni_eternal_story])
    end
  end

  describe "GET #show" do
    it "assigns the requested alumni_eternal_story as @alumni_eternal_story" do
      alumni_eternal_story = AlumniEternalStory.create! valid_attributes
      get :show, {:id => alumni_eternal_story.to_param}, valid_session
      expect(assigns(:alumni_eternal_story)).to eq(alumni_eternal_story)
    end
  end

  describe "GET #new" do
    it "assigns a new alumni_eternal_story as @alumni_eternal_story" do
      get :new, {}, valid_session
      expect(assigns(:alumni_eternal_story)).to be_a_new(AlumniEternalStory)
    end
  end

  describe "GET #edit" do
    it "assigns the requested alumni_eternal_story as @alumni_eternal_story" do
      alumni_eternal_story = AlumniEternalStory.create! valid_attributes
      get :edit, {:id => alumni_eternal_story.to_param}, valid_session
      expect(assigns(:alumni_eternal_story)).to eq(alumni_eternal_story)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AlumniEternalStory" do
        expect {
          post :create, {:alumni_eternal_story => valid_attributes}, valid_session
        }.to change(AlumniEternalStory, :count).by(1)
      end

      it "assigns a newly created alumni_eternal_story as @alumni_eternal_story" do
        post :create, {:alumni_eternal_story => valid_attributes}, valid_session
        expect(assigns(:alumni_eternal_story)).to be_a(AlumniEternalStory)
        expect(assigns(:alumni_eternal_story)).to be_persisted
      end

      it "redirects to the created alumni_eternal_story" do
        post :create, {:alumni_eternal_story => valid_attributes}, valid_session
        expect(response).to redirect_to(AlumniEternalStory.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved alumni_eternal_story as @alumni_eternal_story" do
        post :create, {:alumni_eternal_story => invalid_attributes}, valid_session
        expect(assigns(:alumni_eternal_story)).to be_a_new(AlumniEternalStory)
      end

      it "re-renders the 'new' template" do
        post :create, {:alumni_eternal_story => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            user_id:  1,
            story: 'Updated Something touching about an alumni',
            alumni_eternal_id: 1
        }
      }

      it "updates the requested alumni_eternal_story" do
        alumni_eternal_story = AlumniEternalStory.create! valid_attributes
        put :update, {:id => alumni_eternal_story.to_param, :alumni_eternal_story => new_attributes}, valid_session
        alumni_eternal_story.reload
        expect(alumni_eternal_story.attributes).to include( { 'story' => 'Updated Something touching about an alumni' } )
      end

      it "assigns the requested alumni_eternal_story as @alumni_eternal_story" do
        alumni_eternal_story = AlumniEternalStory.create! valid_attributes
        put :update, {:id => alumni_eternal_story.to_param, :alumni_eternal_story => valid_attributes}, valid_session
        expect(assigns(:alumni_eternal_story)).to eq(alumni_eternal_story)
      end

      it "redirects to the alumni_eternal_story" do
        alumni_eternal_story = AlumniEternalStory.create! valid_attributes
        put :update, {:id => alumni_eternal_story.to_param, :alumni_eternal_story => valid_attributes}, valid_session
        expect(response).to redirect_to(alumni_eternal_story)
      end
    end

    context "with invalid params" do
      it "assigns the alumni_eternal_story as @alumni_eternal_story" do
        alumni_eternal_story = AlumniEternalStory.create! valid_attributes
        put :update, {:id => alumni_eternal_story.to_param, :alumni_eternal_story => invalid_attributes}, valid_session
        expect(assigns(:alumni_eternal_story)).to eq(alumni_eternal_story)
      end

      it "re-renders the 'edit' template" do
        alumni_eternal_story = AlumniEternalStory.create! valid_attributes
        put :update, {:id => alumni_eternal_story.to_param, :alumni_eternal_story => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested alumni_eternal_story" do
      alumni_eternal_story = AlumniEternalStory.create! valid_attributes
      expect {
        delete :destroy, {:id => alumni_eternal_story.to_param}, valid_session
      }.to change(AlumniEternalStory, :count).by(-1)
    end

    it "redirects to the alumni_eternal_stories list" do
      alumni_eternal_story = AlumniEternalStory.create! valid_attributes
      delete :destroy, {:id => alumni_eternal_story.to_param}, valid_session
      expect(response).to redirect_to(alumni_eternal_stories_url)
    end
  end

end
