require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CurrentResidencesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CurrentResidence. As you add validations to CurrentResidence, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CurrentResidencesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all current_residences as @current_residences" do
      current_residence = CurrentResidence.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:current_residences)).to eq([current_residence])
    end
  end

  describe "GET #show" do
    it "assigns the requested current_residence as @current_residence" do
      current_residence = CurrentResidence.create! valid_attributes
      get :show, {:id => current_residence.to_param}, valid_session
      expect(assigns(:current_residence)).to eq(current_residence)
    end
  end

  describe "GET #new" do
    it "assigns a new current_residence as @current_residence" do
      get :new, {}, valid_session
      expect(assigns(:current_residence)).to be_a_new(CurrentResidence)
    end
  end

  describe "GET #edit" do
    it "assigns the requested current_residence as @current_residence" do
      current_residence = CurrentResidence.create! valid_attributes
      get :edit, {:id => current_residence.to_param}, valid_session
      expect(assigns(:current_residence)).to eq(current_residence)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CurrentResidence" do
        expect {
          post :create, {:current_residence => valid_attributes}, valid_session
        }.to change(CurrentResidence, :count).by(1)
      end

      it "assigns a newly created current_residence as @current_residence" do
        post :create, {:current_residence => valid_attributes}, valid_session
        expect(assigns(:current_residence)).to be_a(CurrentResidence)
        expect(assigns(:current_residence)).to be_persisted
      end

      it "redirects to the created current_residence" do
        post :create, {:current_residence => valid_attributes}, valid_session
        expect(response).to redirect_to(CurrentResidence.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved current_residence as @current_residence" do
        post :create, {:current_residence => invalid_attributes}, valid_session
        expect(assigns(:current_residence)).to be_a_new(CurrentResidence)
      end

      it "re-renders the 'new' template" do
        post :create, {:current_residence => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested current_residence" do
        current_residence = CurrentResidence.create! valid_attributes
        put :update, {:id => current_residence.to_param, :current_residence => new_attributes}, valid_session
        current_residence.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested current_residence as @current_residence" do
        current_residence = CurrentResidence.create! valid_attributes
        put :update, {:id => current_residence.to_param, :current_residence => valid_attributes}, valid_session
        expect(assigns(:current_residence)).to eq(current_residence)
      end

      it "redirects to the current_residence" do
        current_residence = CurrentResidence.create! valid_attributes
        put :update, {:id => current_residence.to_param, :current_residence => valid_attributes}, valid_session
        expect(response).to redirect_to(current_residence)
      end
    end

    context "with invalid params" do
      it "assigns the current_residence as @current_residence" do
        current_residence = CurrentResidence.create! valid_attributes
        put :update, {:id => current_residence.to_param, :current_residence => invalid_attributes}, valid_session
        expect(assigns(:current_residence)).to eq(current_residence)
      end

      it "re-renders the 'edit' template" do
        current_residence = CurrentResidence.create! valid_attributes
        put :update, {:id => current_residence.to_param, :current_residence => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested current_residence" do
      current_residence = CurrentResidence.create! valid_attributes
      expect {
        delete :destroy, {:id => current_residence.to_param}, valid_session
      }.to change(CurrentResidence, :count).by(-1)
    end

    it "redirects to the current_residences list" do
      current_residence = CurrentResidence.create! valid_attributes
      delete :destroy, {:id => current_residence.to_param}, valid_session
      expect(response).to redirect_to(current_residences_url)
    end
  end

end
