require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FlowerDeliveriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # FlowerDelivery. As you add validations to FlowerDelivery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FlowerDeliveriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all flower_deliveries as @flower_deliveries" do
      flower_delivery = FlowerDelivery.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:flower_deliveries)).to eq([flower_delivery])
    end
  end

  describe "GET show" do
    it "assigns the requested flower_delivery as @flower_delivery" do
      flower_delivery = FlowerDelivery.create! valid_attributes
      get :show, {:id => flower_delivery.to_param}, valid_session
      expect(assigns(:flower_delivery)).to eq(flower_delivery)
    end
  end

  describe "GET new" do
    it "assigns a new flower_delivery as @flower_delivery" do
      get :new, {}, valid_session
      expect(assigns(:flower_delivery)).to be_a_new(FlowerDelivery)
    end
  end

  describe "GET edit" do
    it "assigns the requested flower_delivery as @flower_delivery" do
      flower_delivery = FlowerDelivery.create! valid_attributes
      get :edit, {:id => flower_delivery.to_param}, valid_session
      expect(assigns(:flower_delivery)).to eq(flower_delivery)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FlowerDelivery" do
        expect {
          post :create, {:flower_delivery => valid_attributes}, valid_session
        }.to change(FlowerDelivery, :count).by(1)
      end

      it "assigns a newly created flower_delivery as @flower_delivery" do
        post :create, {:flower_delivery => valid_attributes}, valid_session
        expect(assigns(:flower_delivery)).to be_a(FlowerDelivery)
        expect(assigns(:flower_delivery)).to be_persisted
      end

      it "redirects to the created flower_delivery" do
        post :create, {:flower_delivery => valid_attributes}, valid_session
        expect(response).to redirect_to(FlowerDelivery.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved flower_delivery as @flower_delivery" do
        post :create, {:flower_delivery => invalid_attributes}, valid_session
        expect(assigns(:flower_delivery)).to be_a_new(FlowerDelivery)
      end

      it "re-renders the 'new' template" do
        post :create, {:flower_delivery => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested flower_delivery" do
        flower_delivery = FlowerDelivery.create! valid_attributes
        put :update, {:id => flower_delivery.to_param, :flower_delivery => new_attributes}, valid_session
        flower_delivery.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested flower_delivery as @flower_delivery" do
        flower_delivery = FlowerDelivery.create! valid_attributes
        put :update, {:id => flower_delivery.to_param, :flower_delivery => valid_attributes}, valid_session
        expect(assigns(:flower_delivery)).to eq(flower_delivery)
      end

      it "redirects to the flower_delivery" do
        flower_delivery = FlowerDelivery.create! valid_attributes
        put :update, {:id => flower_delivery.to_param, :flower_delivery => valid_attributes}, valid_session
        expect(response).to redirect_to(flower_delivery)
      end
    end

    describe "with invalid params" do
      it "assigns the flower_delivery as @flower_delivery" do
        flower_delivery = FlowerDelivery.create! valid_attributes
        put :update, {:id => flower_delivery.to_param, :flower_delivery => invalid_attributes}, valid_session
        expect(assigns(:flower_delivery)).to eq(flower_delivery)
      end

      it "re-renders the 'edit' template" do
        flower_delivery = FlowerDelivery.create! valid_attributes
        put :update, {:id => flower_delivery.to_param, :flower_delivery => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested flower_delivery" do
      flower_delivery = FlowerDelivery.create! valid_attributes
      expect {
        delete :destroy, {:id => flower_delivery.to_param}, valid_session
      }.to change(FlowerDelivery, :count).by(-1)
    end

    it "redirects to the flower_deliveries list" do
      flower_delivery = FlowerDelivery.create! valid_attributes
      delete :destroy, {:id => flower_delivery.to_param}, valid_session
      expect(response).to redirect_to(flower_deliveries_url)
    end
  end

end
