require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PaddlesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Paddle. As you add validations to Paddle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
        pledge_class: '1967',
        picture: 'https://s3.amazonaws.com/phitau/test/paddle1.jpg'
    }
  }

  let(:invalid_attributes) {
    {
        pledge_class: nil,
        picture: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaddlesController. Be sure to keep this updated too.
  let(:valid_session) {
    @user = FactoryGirl.create(:user)
    sign_in :user, @user
  }

  describe "GET #index" do
    it "assigns all paddles as @paddles" do
      paddle = Paddle.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:paddles)).to eq([paddle])
    end
  end

  describe "GET #show" do
    it "assigns the requested paddle as @paddle" do
      paddle = Paddle.create! valid_attributes
      get :show, {:id => paddle.to_param}, valid_session
      expect(assigns(:paddle)).to eq(paddle)
    end
  end

  describe "GET #new" do
    it "assigns a new paddle as @paddle" do
      get :new, {}, valid_session
      expect(assigns(:paddle)).to be_a_new(Paddle)
    end
  end

  describe "GET #edit" do
    it "assigns the requested paddle as @paddle" do
      paddle = Paddle.create! valid_attributes
      get :edit, {:id => paddle.to_param}, valid_session
      expect(assigns(:paddle)).to eq(paddle)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Paddle" do
        expect {
          post :create, {:paddle => valid_attributes}, valid_session
        }.to change(Paddle, :count).by(1)
      end

      it "assigns a newly created paddle as @paddle" do
        post :create, {:paddle => valid_attributes}, valid_session
        expect(assigns(:paddle)).to be_a(Paddle)
        expect(assigns(:paddle)).to be_persisted
      end

      it "redirects to the created paddle" do
        post :create, {:paddle => valid_attributes}, valid_session
        expect(response).to redirect_to(Paddle.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved paddle as @paddle" do
        post :create, {:paddle => invalid_attributes}, valid_session
        expect(assigns(:paddle)).to be_a_new(Paddle)
      end

      it "re-renders the 'new' template" do
        post :create, {:paddle => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            pledge_class: '1984',
            picture: 'https://s3.amazonaws.com/phitau/test/paddle2.jpg'
        }
      }

      it "updates the requested paddle" do
        paddle = Paddle.create! valid_attributes
        put :update, {:id => paddle.to_param, :paddle => new_attributes}, valid_session
        paddle.reload
        expect(assigns(:paddle).attributes[:pledge_class]).to match(new_attributes[:pledge_class])
      end

      it "assigns the requested paddle as @paddle" do
        paddle = Paddle.create! valid_attributes
        put :update, {:id => paddle.to_param, :paddle => valid_attributes}, valid_session
        expect(assigns(:paddle)).to eq(paddle)
      end

      it "redirects to the paddle" do
        paddle = Paddle.create! valid_attributes
        put :update, {:id => paddle.to_param, :paddle => valid_attributes}, valid_session
        expect(response).to redirect_to(paddle)
      end
    end

    context "with invalid params" do
      it "assigns the paddle as @paddle" do
        paddle = Paddle.create! valid_attributes
        put :update, {:id => paddle.to_param, :paddle => invalid_attributes}, valid_session
        expect(assigns(:paddle)).to eq(paddle)
      end

      it "re-renders the 'edit' template" do
        paddle = Paddle.create! valid_attributes
        put :update, {:id => paddle.to_param, :paddle => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested paddle" do
      paddle = Paddle.create! valid_attributes
      expect {
        delete :destroy, {:id => paddle.to_param}, valid_session
      }.to change(Paddle, :count).by(-1)
    end

    it "redirects to the paddles list" do
      paddle = Paddle.create! valid_attributes
      delete :destroy, {:id => paddle.to_param}, valid_session
      expect(response).to redirect_to(paddles_url)
    end
  end

end
